In [ ]:
import pandas as pd
import numpy as np


data = {
    'A': [1, 2, np.nan, 4],
    'B': [np.nan, 2, 3, 4],
    'C': [1, np.nan, np.nan, 4]
}
df = pd.to_datetime(df['Day']).dt.date
df = pd.DataFrame(data)
print(df.isnull().sum())
print(df)
df.fillna(df.mean(numeric_only=True), inplace=True )
print(df.isnull().sum())
print(df)

A    1
B    1
C    2
dtype: int64
     A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  3.0  NaN
3  4.0  4.0  4.0
A    0
B    0
C    0
dtype: int64
          A    B    C
0  1.000000  3.0  1.0
1  2.000000  2.0  2.5
2  2.333333  3.0  2.5
3  4.000000  4.0  4.0


In [2]:
from sklearn.preprocessing import LabelEncoder

colors = ['Red', 'Blue', 'Green', 'Blue', 'Red']
le = LabelEncoder()
encoded_colors = le.fit_transform(colors)
print("Encoded Colors:", encoded_colors)


Encoded Colors: [2 0 1 0 2]


In [3]:
import pandas as pd
df = pd.DataFrame({ 'Colors' : ['Red', 'Blue', 'Green', 'Blue', 'Red'] })

encode = pd.get_dummies(df, columns=['Colors'])
print(encode)

   Colors_Blue  Colors_Green  Colors_Red
0        False         False        True
1         True         False       False
2        False          True       False
3         True         False       False
4        False         False        True


In [4]:
from sklearn.preprocessing import OneHotEncoder

colors = [['Red'] , ['Blue'], ['Green'], ['Blue'], ['Red']]
ohe = OneHotEncoder(sparse_output=False)
encoded_colors = ohe.fit_transform(colors)
print("One-Hot Encoded Colors:\n", encoded_colors)

One-Hot Encoded Colors:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
