In [4]:
import numpy as np
from sklearn.cluster import KMeans
import pandas as pd

df = pd.read_csv('./Data/iris.csv')
X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]

inertias = []
K_values = range(1, 11)

for k in K_values:
    model = KMeans(n_clusters=k, random_state=42)
    model.fit(X)
    inertias.append(model.inertia_)

drops = np.diff(inertias)
optimal_k = np.argmax(drops) + 1

final_model = KMeans(n_clusters=optimal_k, random_state=42)
final_model.fit(X)

print("Optimal k:", optimal_k)
print("Inertia:", final_model.inertia_)
print("\nCluster Centers:")
print(final_model.cluster_centers_)
print("\nCluster Labels:")
print(final_model.labels_)


Optimal k: 9
Inertia: 28.756456196581205

Cluster Centers:
[[6.42777778 2.97777778 4.57222222 1.41666667]
 [4.725      3.13333333 1.42083333 0.19166667]
 [6.72       3.24       5.8        2.33      ]
 [5.65333333 2.80666667 4.22666667 1.32      ]
 [5.39230769 2.43846154 3.65384615 1.12307692]
 [6.54375    2.9875     5.38125    2.03125   ]
 [5.26538462 3.68076923 1.50384615 0.29230769]
 [6.01666667 2.70555556 4.98333333 1.77222222]
 [7.54       3.09       6.36       2.        ]]

Cluster Labels:
[6 1 1 1 6 6 1 1 1 1 6 1 1 1 6 6 6 6 6 6 6 6 1 6 1 1 6 6 6 1 1 6 6 6 1 1 6
 1 1 6 6 1 1 6 6 1 6 1 6 1 0 0 0 4 0 3 0 4 0 4 4 3 4 0 4 0 3 3 7 4 7 3 7 0
 0 0 0 5 0 4 4 4 3 7 3 0 0 0 3 4 3 0 3 4 3 3 3 0 4 3 2 7 2 5 2 8 3 8 5 2 5
 5 5 7 7 5 5 8 8 7 2 7 8 7 2 8 7 7 5 8 8 8 5 7 7 8 2 5 7 5 2 5 7 2 2 5 7 5
 5 7]
